### ISSUE TITLE
The RTL classes can't be applied to @apply 

### ISSUE THREAD

**Issue by samoel02** [20lives/tailwindcss-rtl#1]
I'm trying to add custom rtl classes to @apply variable and I get this error<br><br>`@apply cannot be used with .ps-4 because .ps-4 either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that .ps-4 exists, make sure that any @import statements are being properly processed *before* Tailwind CSS sees your CSS, as @apply can only be used for classes in the same CSS tree.`

**Comment by HapLifeMan** [comment]
Unfortunately we would not be able to have it working if we want to add these classes in CSS files directly. That's because the selectors generated by the plugin is too complex and can't be handled by the @apply rule: https://github.com/tailwindcss/tailwindcss/issues/1344#issuecomment-580727001.

As I really want to have an easy way to change directions of my app, I will fork this repo then change the selectors by using the CSS logical properties:
- `margin-inline-start`
- `margin-inline-start`
- `margin-inline-start`

**Comment by 20lives** [comment]
Thank you @HapLifeMan for investigating this issue.
as I said in other discussions I will update those utilities to logical properties.

**Comment by 20lives** [comment]
I have just updated the plugin to use logical properties, so this should be working now if anyone cares to try.
