### ISSUE TITLE
Question: Why does this not use `border-(start|end)-(start|end)-radius`?

### ISSUE THREAD

**Issue by zendesk-criswell** [20lives/tailwindcss-rtl#47]
Honestly curious and figure there's good reason.

**Comment by 20lives** [comment]
hi!
thank you for your suggestion.
it's a good idea, but there is a minor obstacle:
the regular implementation uses top-right-bottom-left which are guessable in this form ``rounded-br-md``, but how can I know which one is the first and second initial in ``rounded-ss-md``?

since this plugin focuses on left and right I can keep the top/bottom and only change start/end on the right/left.

how about that?
